In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("student_admission_record_dirty.csv")

In [5]:
df.head(10)

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
4,Bilal,20.0,Male,65.0,61.13,Lahore,NaN
5,Murtaza,23.0,Female,NaN,NaN,Islamabad,Accepted
6,Asad,18.0,Male,NaN,97.31,Multan,Accepted
7,Rabia,20.0,Female,82.0,55.67,Lahore,Accepted
8,Rohail,17.0,Male,64.0,NaN,Karachi,Accepted
9,Kamran,18.0,Male,53.0,98.98,Multan,Rejected

In [6]:
df.tail()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
152,Ali,19.0,Female,85.0,78.09,Quetta,Accepted
153,Bilal,17.0,Female,81.0,84.40,Islamabad,Rejected
154,Fatima,21.0,Female,98.0,50.86,Multan,Accepted
155,Shoaib,-1.0,Male,91.0,80.12,Quetta,Accepted
156,Maaz,17.0,Male,88.0,86.85,Lahore,Accepted

In [8]:
df.shape

(157, 7)

In [9]:
df.columns

Index(['Name', 'Age', 'Gender', 'Admission Test Score',
       'High School Percentage', 'City', 'Admission Status'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    147 non-null    object
 1   Age                     147 non-null    float64
 2   Gender                  147 non-null    object
 3   Admission Test Score    146 non-null    float64
 4   High School Percentage  146 non-null    float64
 5   City                    147 non-null    object
 6   Admission Status        147 non-null    object
dtypes: float64(3), object(4)
memory usage: 8.7+ KB

In [15]:
df.isnull()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True
2,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...
152,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False
154,False,False,False,False,False,False,False
155,False,False,False,False,False,False,False
156,False,False,False,False,False,False,False

In [16]:
df.isnull().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [17]:
df.describe()

              Age  Admission Test Score  High School Percentage
count  147.000000            146.000000              146.000000
mean    19.680272             77.657534               75.684726
std      4.540512             16.855343               17.368014
min     -1.000000             -5.000000              -10.000000
25%     18.000000             68.250000               65.052500
50%     20.000000             79.000000               77.545000
75%     22.000000             89.000000               88.312500
max     24.000000            150.000000              110.500000

In [18]:
df.ndim

2

In [21]:
df.dtypes

Name                       object
Age                       float64
Gender                     object
Admission Test Score      float64
High School Percentage    float64
City                       object
Admission Status           object
dtype: object

In [23]:
df['Age'] = df['Age'].astype('Int64')

In [32]:
df.dtypes

Name                       object
Age                         Int64
Gender                     object
Admission Test Score      float64
High School Percentage    float64
City                       object
Admission Status           object
dtype: object

In [37]:
df.isnull().sum()

Name                      10
Age                        0
Gender                    10
Admission Test Score      11
High School Percentage     0
City                      10
Admission Status          10
dtype: int64

In [34]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [36]:
df['High School Percentage']=df['High School Percentage'].fillna(df['High School Percentage'].mean())

In [39]:
df.head()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24,Female,50.0,68.900000,Quetta,Rejected
1,Waqar,21,Female,99.0,60.730000,Karachi,NaN
2,Bushra,17,Male,89.0,75.684726,Islamabad,Accepted
3,Aliya,17,Male,55.0,85.290000,Karachi,Rejected
4,Bilal,20,Male,65.0,61.130000,Lahore,NaN

In [42]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

In [45]:
df.head()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24,1.0,50.0,68.900000,Quetta,0.0
1,Waqar,21,1.0,99.0,60.730000,Karachi,NaN
2,Bushra,17,0.0,89.0,75.684726,Islamabad,1.0
3,Aliya,17,0.0,55.0,85.290000,Karachi,0.0
4,Bilal,20,0.0,65.0,61.130000,Lahore,NaN

In [44]:
df['Admission Status'] = df['Admission Status'].map({'Rejected': 0, 'Accepted': 1})

In [46]:
df.head()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24,1.0,50.0,68.900000,Quetta,0.0
1,Waqar,21,1.0,99.0,60.730000,Karachi,NaN
2,Bushra,17,0.0,89.0,75.684726,Islamabad,1.0
3,Aliya,17,0.0,55.0,85.290000,Karachi,0.0
4,Bilal,20,0.0,65.0,61.130000,Lahore,NaN